---
# c9devel.yaml - playbook for creating a LinuxJedi devel bastion from
# an ljbase AMI created with ljstandard.yaml

# note: run aws_init first to create the build user

- hosts: "{{ target }}"
  remote_user: build
  tasks:
  - name: Set mountpoints for a Cloud9 developer instances
    set_fact:
      remote_user: build
      mount_points:
      - dir_name: home
        mount_point: /home
      - dir_name: www
        mount_point: /var/www
      - dir_name: httpconf
        mount_point: /etc/httpd/conf.d
      - dir_name: ssl
        mount_point: /etc/pki
# platform-specific definitions including data volumes
- name: Set platform-specific variables
  import_playbook: platform-vars.yaml

- hosts: "{{ target }}"
  name: Set up data volume and users
  become: yes
  remote_user: build
  tasks:
  - name: Remove launch user
    user:
      name: "{{ build_remote }}"
      state: absent
      remove: yes
      force: yes
  - name: Data Volume role
    import_role:
      name: data_vol_single
  - name: Create Users role
    import_role:
      name: ansible-users
  - name: Copy Cloud9 Install script
    copy:
      src: files/c9install.sh
      dest: /usr/local/bin/c9install.sh
      mode: 0755
  - name: Install Cloud9 for Users
    become_user: "{{ item.username }}"
    command: /usr/local/bin/c9install.sh
    args:
      creates: "/home/{{ item.username }}/.c9"
    with_items: "{{ users }}"
  - name: Create User .ssh directory
    file:
      path: "/home/{{ item.username }}/.ssh"
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
      state: directory
      mode: 0700
    with_items: "{{ users }}"
  - name: Install the User's SSH key
    copy:
        src: "files/{{ item.username }}/id_rsa"
        dest: "/home/{{ item.username }}/.ssh/id_rsa"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0600
    with_items: "{{ users }}"
  - name: Install the User's SSH config
    copy:
        src: "files/{{ item.username }}/ssh-config"
        dest: "/home/{{ item.username }}/.ssh/config"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0600
    with_items: "{{ users }}"

- hosts: "{{ target }}"
  name: Remove build user authorized keys
  become: yes
  remote_user: build
  tasks:
  - file:
      path: /build/.ssh/authorized_keys
      state: absent
  - user:
      name: build
      state: absent
      force: yes
