---
- name: Create Partition
  shell: 'echo ",,83" | sfdisk {{ data_vol_dev }}'
  args:
    creates: "{{ data_vol_part }}"
- name: Wait for Partition
  wait_for:
    path: "{{ data_vol_part }}"
- name: Create Filesystem
  filesystem: "fstype={{ new_fs_type }} dev={{ data_vol_part }}"
- name: Mount Data Volume
  mount: name=/data src={{ data_vol_part }} fstype={{ new_fs_type }} opts=nodev state=mounted
- name: Set Data Mount Permissions
  file: path=/data mode=0700
- include: copy.yaml
  with_items: "{{ mount_points }}"
